#ifndef FANTASI_DISPLAY_H
#define FANTASI_DISPLAY_H

#include <stdint.h>
#include <stdbool.h>

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64
#define DISPLAY_PAGES   8
#define DISPLAY_COLS    21  /* 128 / 6 (5px glyph + 1px gap) */
#define DISPLAY_ROWS    8   /* 64 / 8 (7px glyph + 1px gap) */

/* Extra glyphs past printable ASCII (in both the 5x7 grid font and the
 * proportional fonts below). */
#define DISPLAY_CHAR_UP   "\x7F"
#define DISPLAY_CHAR_DOWN "\x80"

/* Proportional bitmap font, generated by gen_font.py into font_data.c.
 * Glyph columns are 16 bits tall, bit 0 = top row of the glyph's own
 * bounding box; `ytop` places that box relative to the text top (the
 * ascent line), so descenders land below the baseline. */
typedef struct {
    uint8_t  w;       /* bitmap width in columns (0 = blank, e.g. space) */
    uint8_t  adv;     /* pen advance to the next glyph */
    int8_t   xoff;    /* bitmap left offset from the pen position */
    int8_t   ytop;    /* bitmap top offset from the text top */
    uint16_t off;     /* first column index into cols[] */
} fz_glyph_t;

typedef struct {
    uint8_t ascent;   /* rows from text top to baseline */
    uint8_t descent;  /* rows below the baseline */
    uint8_t first, last;
    const fz_glyph_t *glyphs;
    const uint16_t   *cols;
} fz_font_t;

extern const fz_font_t font_item;   /* haxrcorp 4089 - stock FZ menu font  */
extern const fz_font_t font_bold;   /* Helvetica Bold 8 - stock FZ titles  */

void display_init(void);
void display_clear(void);
void display_print(int col, int row, const char *str);
void display_print_inv(int col, int row, const char *str);
void display_hline(int y);   /* 1px horizontal line across pixel row y */
void display_fill_rect(int x, int y, int w, int h, bool on);
void display_text(const fz_font_t *f, int x, int y, const char *str, bool inverse);
int  display_text_width(const fz_font_t *f, const char *str);
void display_button(int cx, int y, const char *label);
void display_blit(const uint8_t *data, uint32_t len);
void display_flush(void);

/* Hold across any compose+flush sequence that can run concurrently with
 * another task's drawing (see the file header in display.c). */
void display_lock(void);
void display_unlock(void);

#endif
