/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FANTASI_PB_H_INCLUDED
#define PB_FANTASI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(512) FileWriteChunk_data_t;
typedef struct _FileWriteChunk {
    char path[64];
    uint32_t offset;
    FileWriteChunk_data_t data;
    bool last;
    bool has_total;
    uint32_t total; /* full file size hint; lets ramfs reserve once */
} FileWriteChunk;

typedef struct _FileReadRequest {
    char path[64];
    uint32_t offset;
    uint32_t size;
} FileReadRequest;

typedef PB_BYTES_ARRAY_T(512) FileReadChunk_data_t;
typedef struct _FileReadChunk {
    uint32_t offset;
    FileReadChunk_data_t data;
    bool last;
} FileReadChunk;

typedef struct _ErrorResponse {
    char message[64];
} ErrorResponse;

typedef struct _DirListRequest {
    char path[64];
} DirListRequest;

typedef struct _DirEntry {
    char name[64];
    bool is_dir;
    uint32_t size;
} DirEntry;

typedef struct _CliResponse {
    uint32_t id;
    bool has_next;
    pb_size_t which_payload;
    union {
        char output[512];
        FileReadChunk file_data;
        ErrorResponse error;
        DirEntry dir_entry;
        /* Device->host: a running app is asking for a feature module by name; the
     host answers with FileWriteChunk(s) into /ramfs. id echoes the app_launch. */
        char module_request[32];
    } payload;
} CliResponse;

typedef struct _FileDeleteRequest {
    char path[64];
} FileDeleteRequest;

typedef struct _MkdirRequest {
    char path[64];
} MkdirRequest;

typedef struct _FileRenameRequest {
    char src[64];
    char dst[64];
} FileRenameRequest;

typedef PB_BYTES_ARRAY_T(64) CliRequest_app_input_t;
typedef struct _CliRequest {
    uint32_t id;
    pb_size_t which_payload;
    union {
        char command[128];
        FileWriteChunk file_write;
        FileReadRequest file_read;
        DirListRequest dir_list;
        FileDeleteRequest file_delete;
        MkdirRequest mkdir;
        /* Async app session (host CLI `rfid` and any interactive launch): app_launch
     starts the app and returns immediately (unlike `command "launch ..."`,
     which streams synchronously); app_input feeds keystrokes to the running
     app; app_stop aborts it (the ^C equivalent). */
        char app_launch[64];
        CliRequest_app_input_t app_input;
        bool app_stop;
        FileRenameRequest file_rename;
    } payload;
} CliRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CliRequest_init_default                  {0, 0, {""}}
#define CliResponse_init_default                 {0, 0, 0, {""}}
#define FileWriteChunk_init_default              {"", 0, {0, {0}}, 0, false, 0}
#define FileReadRequest_init_default             {"", 0, 0}
#define FileReadChunk_init_default               {0, {0, {0}}, 0}
#define ErrorResponse_init_default               {""}
#define DirListRequest_init_default              {""}
#define DirEntry_init_default                    {"", 0, 0}
#define FileDeleteRequest_init_default           {""}
#define MkdirRequest_init_default                {""}
#define FileRenameRequest_init_default           {"", ""}
#define CliRequest_init_zero                     {0, 0, {""}}
#define CliResponse_init_zero                    {0, 0, 0, {""}}
#define FileWriteChunk_init_zero                 {"", 0, {0, {0}}, 0, false, 0}
#define FileReadRequest_init_zero                {"", 0, 0}
#define FileReadChunk_init_zero                  {0, {0, {0}}, 0}
#define ErrorResponse_init_zero                  {""}
#define DirListRequest_init_zero                 {""}
#define DirEntry_init_zero                       {"", 0, 0}
#define FileDeleteRequest_init_zero              {""}
#define MkdirRequest_init_zero                   {""}
#define FileRenameRequest_init_zero              {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define FileWriteChunk_path_tag                  1
#define FileWriteChunk_offset_tag                2
#define FileWriteChunk_data_tag                  3
#define FileWriteChunk_last_tag                  4
#define FileWriteChunk_total_tag                 5
#define FileReadRequest_path_tag                 1
#define FileReadRequest_offset_tag               2
#define FileReadRequest_size_tag                 3
#define FileReadChunk_offset_tag                 1
#define FileReadChunk_data_tag                   2
#define FileReadChunk_last_tag                   3
#define ErrorResponse_message_tag                1
#define DirListRequest_path_tag                  1
#define DirEntry_name_tag                        1
#define DirEntry_is_dir_tag                      2
#define DirEntry_size_tag                        3
#define CliResponse_id_tag                       1
#define CliResponse_has_next_tag                 2
#define CliResponse_output_tag                   3
#define CliResponse_file_data_tag                4
#define CliResponse_error_tag                    5
#define CliResponse_dir_entry_tag                6
#define CliResponse_module_request_tag           7
#define FileDeleteRequest_path_tag               1
#define MkdirRequest_path_tag                    1
#define FileRenameRequest_src_tag                1
#define FileRenameRequest_dst_tag                2
#define CliRequest_id_tag                        1
#define CliRequest_command_tag                   2
#define CliRequest_file_write_tag                3
#define CliRequest_file_read_tag                 4
#define CliRequest_dir_list_tag                  5
#define CliRequest_file_delete_tag               6
#define CliRequest_mkdir_tag                     7
#define CliRequest_app_launch_tag                8
#define CliRequest_app_input_tag                 9
#define CliRequest_app_stop_tag                  10
#define CliRequest_file_rename_tag               11

/* Struct field encoding specification for nanopb */
#define CliRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    STRING,   (payload,command,payload.command),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_write,payload.file_write),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_read,payload.file_read),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dir_list,payload.dir_list),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_delete,payload.file_delete),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mkdir,payload.mkdir),   7) \
X(a, STATIC,   ONEOF,    STRING,   (payload,app_launch,payload.app_launch),   8) \
X(a, STATIC,   ONEOF,    BYTES,    (payload,app_input,payload.app_input),   9) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,app_stop,payload.app_stop),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_rename,payload.file_rename),  11)
#define CliRequest_CALLBACK NULL
#define CliRequest_DEFAULT NULL
#define CliRequest_payload_file_write_MSGTYPE FileWriteChunk
#define CliRequest_payload_file_read_MSGTYPE FileReadRequest
#define CliRequest_payload_dir_list_MSGTYPE DirListRequest
#define CliRequest_payload_file_delete_MSGTYPE FileDeleteRequest
#define CliRequest_payload_mkdir_MSGTYPE MkdirRequest
#define CliRequest_payload_file_rename_MSGTYPE FileRenameRequest

#define CliResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   REQUIRED, BOOL,     has_next,          2) \
X(a, STATIC,   ONEOF,    STRING,   (payload,output,payload.output),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,file_data,payload.file_data),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,error,payload.error),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,dir_entry,payload.dir_entry),   6) \
X(a, STATIC,   ONEOF,    STRING,   (payload,module_request,payload.module_request),   7)
#define CliResponse_CALLBACK NULL
#define CliResponse_DEFAULT NULL
#define CliResponse_payload_file_data_MSGTYPE FileReadChunk
#define CliResponse_payload_error_MSGTYPE ErrorResponse
#define CliResponse_payload_dir_entry_MSGTYPE DirEntry

#define FileWriteChunk_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   REQUIRED, UINT32,   offset,            2) \
X(a, STATIC,   REQUIRED, BYTES,    data,              3) \
X(a, STATIC,   REQUIRED, BOOL,     last,              4) \
X(a, STATIC,   OPTIONAL, UINT32,   total,             5)
#define FileWriteChunk_CALLBACK NULL
#define FileWriteChunk_DEFAULT NULL

#define FileReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1) \
X(a, STATIC,   REQUIRED, UINT32,   offset,            2) \
X(a, STATIC,   REQUIRED, UINT32,   size,              3)
#define FileReadRequest_CALLBACK NULL
#define FileReadRequest_DEFAULT NULL

#define FileReadChunk_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   offset,            1) \
X(a, STATIC,   REQUIRED, BYTES,    data,              2) \
X(a, STATIC,   REQUIRED, BOOL,     last,              3)
#define FileReadChunk_CALLBACK NULL
#define FileReadChunk_DEFAULT NULL

#define ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   message,           1)
#define ErrorResponse_CALLBACK NULL
#define ErrorResponse_DEFAULT NULL

#define DirListRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1)
#define DirListRequest_CALLBACK NULL
#define DirListRequest_DEFAULT NULL

#define DirEntry_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, BOOL,     is_dir,            2) \
X(a, STATIC,   REQUIRED, UINT32,   size,              3)
#define DirEntry_CALLBACK NULL
#define DirEntry_DEFAULT NULL

#define FileDeleteRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1)
#define FileDeleteRequest_CALLBACK NULL
#define FileDeleteRequest_DEFAULT NULL

#define MkdirRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   path,              1)
#define MkdirRequest_CALLBACK NULL
#define MkdirRequest_DEFAULT NULL

#define FileRenameRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   src,               1) \
X(a, STATIC,   REQUIRED, STRING,   dst,               2)
#define FileRenameRequest_CALLBACK NULL
#define FileRenameRequest_DEFAULT NULL

extern const pb_msgdesc_t CliRequest_msg;
extern const pb_msgdesc_t CliResponse_msg;
extern const pb_msgdesc_t FileWriteChunk_msg;
extern const pb_msgdesc_t FileReadRequest_msg;
extern const pb_msgdesc_t FileReadChunk_msg;
extern const pb_msgdesc_t ErrorResponse_msg;
extern const pb_msgdesc_t DirListRequest_msg;
extern const pb_msgdesc_t DirEntry_msg;
extern const pb_msgdesc_t FileDeleteRequest_msg;
extern const pb_msgdesc_t MkdirRequest_msg;
extern const pb_msgdesc_t FileRenameRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CliRequest_fields &CliRequest_msg
#define CliResponse_fields &CliResponse_msg
#define FileWriteChunk_fields &FileWriteChunk_msg
#define FileReadRequest_fields &FileReadRequest_msg
#define FileReadChunk_fields &FileReadChunk_msg
#define ErrorResponse_fields &ErrorResponse_msg
#define DirListRequest_fields &DirListRequest_msg
#define DirEntry_fields &DirEntry_msg
#define FileDeleteRequest_fields &FileDeleteRequest_msg
#define MkdirRequest_fields &MkdirRequest_msg
#define FileRenameRequest_fields &FileRenameRequest_msg

/* Maximum encoded size of messages (where known) */
#define CliRequest_size                          603
#define CliResponse_size                         534
#define DirEntry_size                            73
#define DirListRequest_size                      65
#define ErrorResponse_size                       65
#define FANTASI_PB_H_MAX_SIZE                    CliRequest_size
#define FileDeleteRequest_size                   65
#define FileReadChunk_size                       523
#define FileReadRequest_size                     77
#define FileRenameRequest_size                   130
#define FileWriteChunk_size                      594
#define MkdirRequest_size                        65

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
