/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "fantasi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CliRequest, CliRequest, 2)


PB_BIND(CliResponse, CliResponse, 2)


PB_BIND(CancelRequest, CancelRequest, AUTO)


PB_BIND(FileWriteChunk, FileWriteChunk, 2)


PB_BIND(FileReadRequest, FileReadRequest, AUTO)


PB_BIND(FileReadChunk, FileReadChunk, 2)


PB_BIND(ErrorResponse, ErrorResponse, AUTO)


PB_BIND(DirListRequest, DirListRequest, AUTO)


PB_BIND(DirEntry, DirEntry, AUTO)


PB_BIND(FileDeleteRequest, FileDeleteRequest, AUTO)


PB_BIND(MkdirRequest, MkdirRequest, AUTO)


PB_BIND(FileRenameRequest, FileRenameRequest, AUTO)



