#!/usr/bin/env python3
"""Unit test: the committed nanopb sources match proto/fantasi.proto.

Regenerates proto/fantasi.pb.{c,h} from the .proto into a temp dir with the
same invocation as `make proto`, and diffs against the committed files. Fails
if they have drifted (fix with `make proto`). Hardware-free - safe for CI.

nanopb output is generator-version-specific, so this only enforces the strict
comparison when the installed generator matches the version the committed files
were produced with; otherwise it SKIPs (a different local nanopb shouldn't fail
the suite - CI pins the version).
"""
import argparse
import difflib
import os
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
GEN_FILES = ["fantasi.pb.c", "fantasi.pb.h"]
EXPECTED_NANOPB = "0.4.9.1"   # matches the "Generated by nanopb-x" header


def skip(msg):
    print(f"SKIP: {msg}")
    sys.exit(77)


def fail(msg):
    print(f"FAIL: {msg}")
    sys.exit(1)


def main():
    # Accept (and ignore) --platform so this can also run under the integration
    # runner; the unit runner invokes it with no args.
    ap = argparse.ArgumentParser()
    ap.add_argument("--platform", default=None)
    ap.parse_args()

    gen = shutil.which("nanopb_generator")
    if not gen:
        skip("nanopb_generator not found (pip install nanopb==%s)" % EXPECTED_NANOPB)

    try:
        ver = subprocess.run([gen, "--version"], capture_output=True, text=True)
        version = (ver.stdout + ver.stderr).strip()
    except Exception as e:
        skip(f"could not query nanopb_generator version: {e}")
    if EXPECTED_NANOPB not in version:
        skip(f"nanopb {version!r} != {EXPECTED_NANOPB} (committed sources are "
             f"version-specific); pin nanopb=={EXPECTED_NANOPB} to enforce")

    with tempfile.TemporaryDirectory() as tmp:
        r = subprocess.run(
            [gen, "proto/fantasi.proto", "-I", "proto",
             "-I", "third_party/nanopb", "-D", tmp],
            cwd=REPO_ROOT, capture_output=True, text=True)
        if r.returncode != 0:
            fail(f"nanopb_generator failed:\n{r.stdout}\n{r.stderr}")

        drift = []
        for f in GEN_FILES:
            regen = os.path.join(tmp, f)
            committed = os.path.join(REPO_ROOT, "proto", f)
            if not os.path.exists(regen):
                fail(f"generator did not produce {f}")
            a = open(committed).read().splitlines(keepends=True)
            b = open(regen).read().splitlines(keepends=True)
            if a != b:
                drift.append(f)
                sys.stdout.writelines(difflib.unified_diff(
                    a, b, f"committed/{f}", f"regenerated/{f}"))

    if drift:
        fail(f"{', '.join(drift)} out of sync with proto/fantasi.proto "
             f"- run `make proto` and commit the result")

    print("PASS: nanopb sources match proto/fantasi.proto")
    sys.exit(0)


if __name__ == "__main__":
    main()
